name: build and release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:  # 允许手动触发
    inputs:
      version:
        description: 'Version (e.g. v0.0.1-test)'
        required: true
        default: 'v0.0.1-test'

permissions:
  contents: write

jobs:
  get-build-info:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.VERSION }}

    steps:
      - name: Get build version
        id: tag
        run: echo "VERSION=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ${{ matrix.os }}
    needs: get-build-info
    env:
      VERSION: ${{ needs.get-build-info.outputs.version }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
            arch: x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc

      - name: Install ARM cross-compiler (Ubuntu)
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install dependencies (macOS)
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew install cmake

      - name: Build myproxy
        run: |
          mkdir build
          cd build
          cmake .. ${CMAKE_ARGS}
          cmake --build .

        env:
          CMAKE_ARGS: >-
            ${{ matrix.target == 'aarch64-unknown-linux-gnu' && '-DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=aarch64' || ''
            }} ${{ startsWith(matrix.os, 'macos') && format('-DCMAKE_OSX_ARCHITECTURES={0}', matrix.arch) || '' }}

      - name: Pack
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd build
          tar czf myproxy-${{ matrix.target }}.tar.gz myproxy
          mv myproxy-${{ matrix.target }}.tar.gz ..

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ needs.get-build-info.outputs.version }}
          file: myproxy-${{ matrix.target }}.tar.gz
          overwrite: true
