name: build and release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. v0.0.1-test)'
        required: true
        default: 'v0.0.1-test'

permissions:
  contents: write

jobs:
  get-build-info:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.VERSION }}

    steps:
      - name: Get build version
        id: tag
        run: echo "VERSION=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ${{ matrix.os }}
    needs: get-build-info
    env:
      VERSION: ${{ needs.get-build-info.outputs.version }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-amd64
          - os: ubuntu-latest
            target: linux-arm64
          - os: macos-latest
            target: darwin-x86_64
          - os: macos-latest
            target: darwin-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc

      - name: Install ARM cross-compiler (Ubuntu ARM64)
        if: matrix.target == 'linux-arm64'
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install dependencies (macOS)
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew install cmake

      - name: Build
        run: make build-${{ matrix.target }}

      - name: Pack
        if: startsWith(github.ref, 'refs/tags/')
        run: make pack-${{ matrix.target }}

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ needs.get-build-info.outputs.version }}
          file: dist/myproxy-*.tar.gz
          file_glob: true
          overwrite: true
